### ISSUE TITLE
ERR_LOCATION_NOT_FOUND too many symbolic links encountered

### ISSUE THREAD

**Issue by ycjcl868** [pranshuchittora/autarky#11]
![image](https://user-images.githubusercontent.com/13595509/69506909-99888600-0f6b-11ea-82a6-b569aea49a5c.png)

**Comment by LoicMahieu** [comment]
Not exactly the same error and I don't know if related:
```
ERR_LOCATION_NOT_FOUND Error: ENOENT: no such file or directory, stat '/Users/loicmahieu/Projects/iGLOO/foo-project/packages/api/node_modules/.bin/ncc'
```

**Comment by pranshuchittora** [comment]
Apologies for the issue 🙏

https://github.com/pranshuchittora/g-factor/blob/66e6124d65df24a396f974afeb771711dad5060d/src/lib/getFilesAndSize.ts#L37

This line was called. Not to worry it won't mess up with your files. It was just used to calculate the size.

@ycjcl868 do you able to run and use the CLI??

**Comment by LoicMahieu** [comment]
Hi @pranshuchittora 
Don't apologies! Thanks for your tool.
I usually clean my node_modules manually and it makes me spare a lot of time. 👍
